server.port=80

spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.url=jdbc:postgresql:///sweater
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.mustache.expose-request-attributes=true
spring.freemarker.expose-request-attributes=true

upload.path=D:/Downloads/SweaterStorage

spring.mail.host=smtp.yandex.ru
spring.mail.password=asgjlmjyfstijgmz
spring.mail.username=kar-dan2000@yandex.ru
spring.mail.port=465
spring.mail.protocol=smtps
mail.debug=true

recaptcha.secret=6LdCZOgUAAAAAGkLN5MZShDS2J8y1-TRPuTOMKxt

spring.session.jdbc.initialize-schema=always
spring.session.jdbc.table-name=SPRING_SESSION